# Generated by Django 3.2.7 on 2021-10-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211024_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'An email is already used.'}, max_length=254, unique=True),
        ),
    ]
