# Generated by Django 3.2.6 on 2021-09-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='print',
            new_name='price',
        ),
    ]
